### ISSUE TITLE
Support exploded WAR deployments in Jetty and Tomcat runtimes

### ISSUE THREAD

**Issue by aslo** [GoogleCloudPlatform/runtime-builder-java#69] opened 2017-07-27 14:26 UTC
The jetty runtime currently has only been tested with WAR file deployments, which are extracted at container start time.  In theory, exploded WARs should be added to the `/app` directory (which is symlinked to  `$JETTY_BASE/webapps/root`).

**Comment by meltsufin** [comment] 2017-10-02 18:54
Duplicate of #44?

**Comment by aslo** [comment] 2017-10-02 18:58
Yep! Feel free to close one of them.

**Closed** 2017-11-21 18:55 UTC
