### ISSUE TITLE
Support exploded WAR deployments

### ISSUE THREAD

**Issue by aslo** [GoogleCloudPlatform/runtime-builder-java#44] opened 2017-05-24 18:19 UTC
In the case of non-exploded wars, the builder should extract them before deploying into the webserver container. Otherwise, the web server container would need to extract the wars every time the container starts up.

**Comment by meltsufin** [comment] 2017-10-02 20:33
Duplicate of #69

**Closed by meltsufin** 2017-10-02 20:33 UTC
